[project]
name = "medval"
version = "0.1.0"
description = "MedVAL: Toward Expert-Level Medical Text Validation with Language Models"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "datasets>=4.4.1",
    "dspy>=3.0.4",
]
